### ISSUE TITLE
warnings in initramfs from 90-coreos-device-mapper.rules

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-config#436] opened 2020-05-29 21:37 UTC
I'm seeing this in a RHCOS `testiso` run:
```
"invalid key/value pair in file /usr/lib/udev/rules.d/90-coreos-device-mapper.rules on line 15, starting at character 53 (',')"
"invalid key/value pair in file /usr/lib/udev/rules.d/90-coreos-device-mapper.rules on line 16, starting at character 56 (',')"

```

**Comment by darkmuggle** [comment] 2020-05-29 21:50
Do you have https://github.com/coreos/fedora-coreos-config/commit/7510b1a405f422d9b5d8c86a80278c64cf082d58 ? That was intended to address this. I suspect RHCOS needs the latest FCOS config.

**Comment by cgwalters** [comment] 2020-05-29 22:02
OK right, https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/983

**Comment by darkmuggle** [comment] 2020-05-29 22:51
RHCOS branch merged. Closing this out.

**Closed as completed by darkmuggle** 2020-05-29 22:51 UTC
