### ISSUE TITLE
Fedore CoreOS enables pwscore dict check, but does not install dictionary

### ISSUE THREAD

**Issue by martinpitt** [coreos/fedora-coreos-config#230] opened 2019-11-12 11:30 UTC
On current Fedora CoreOS (30.20191014.0), pwscore fails:
```
# echo foobarfoo | pwscore 
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Password quality check failed:
 The password fails the dictionary check - error loading dictionary
```
This breaks e. g. Cockpit's Accounts page, it's not possible to add accounts there. This calls pwscore, but passwords are always rejected due to this.

This is essentially the same as https://bugzilla.redhat.com/show_bug.cgi?id=1410450 (in the libpwquality package itself). It got closed as WONTFIX, as from the package's perspective everything is alright: The package recommends dictionaries:
```
# rpm -q --recommends libpwquality
cracklib-dicts >= 2.8
```
So for Fedora CoreOS, either cracklib-dicts should be installed (i. e. Recommends honored), or it should modify /etc/security/pwquality.conf to set `dictcheck=0`.

Version-Release number of selected component (if applicable): libpwquality-1.4.0-12.fc30.x86_64

**Comment by bgilbert** [comment] 2019-11-12 12:52
Duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/308

**Closed as completed by bgilbert** 2019-11-12 12:52 UTC

**Comment by dustymabe** [comment] 2019-11-13 21:17
> Duplicate of [coreos/fedora-coreos-tracker#308](https://github.com/coreos/fedora-coreos-tracker/issues/308)

which was fixed in https://github.com/coreos/fedora-coreos-config/pull/221
