### ISSUE TITLE
Consider to add systemd-netword as an option

### ISSUE THREAD

**Issue by rtsisyk** [coreos/fedora-coreos-config#632] opened 2020-09-22 20:46 UTC
NetworkManager is good software for the desktop, but it is extremely inconvenient to use via configuration files (ingnition, machineconfigoperator). For example, try to create, say, 802.3ad bonding via NetworkManager configuration files without using nm-tui. For me, it is easy to play with /sys/proc/net than to get working NetworkManager via /etc/NetworkManager.

Please consider to add systemd-networkd as an option. I understand that RHEL8/RHCOS uses (and it is one of the most annoying things in RHEL8), but I hope that RHEL9 will move forward and replace NetworkManager via systemd-networkd for server. NetworkManager for desktop (e.g. Fedora Workstation), systemd-networkd for server (CoreOS!).

I propose to add some option to ignition to disable NetworkManager and enable systemd-networkd.

**Comment by bgilbert** [comment] 2020-09-22 21:28
Closing as duplicate of https://github.com/coreos/fedora-coreos-config/pull/574.  The current plan is to try to move systemd-networkd to a subpackage of systemd so users can install it via package layering if they want.  However, networkd will not be a supported or recommended network management option for Fedora CoreOS, for the reasons described in that ticket.

**Closed as completed by bgilbert** 2020-09-22 21:28 UTC
